[package]
name = "hidlights"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "*"
hidparser = "*"
hut = "*"
extfn = "*"
thiserror = "2.0.12"
bitvec = "1"

[dev-dependencies]
eframe = "*"
